version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: nextjs_app
    working_dir: /app
    ports:
      - "3001:3000"
    volumes:
      - .:/app
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=password
      - DB_NAME=my_database
    depends_on:
      - db

  db:
    image: postgres:13
    container_name : fullstack_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: passwd
      POSTGRES_DB: fullstack_db
    ports:  
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
      
volumes:
  postgres-data: