CREATE USER newuser WITH PASSWORD 'passwd';
CREATE DATABASE fullstack_db;
GRANT ALL PRIVILEGES ON DATABASE fullstack_db TO newuser;

\c fullstack_db
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO newuser;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO newuser;
GRANT ALL PRIVILEGES ON ALL FUNCTIONS IN SCHEMA public TO newuser;
